NOTE: Some names were slightly changed due to errors being generated by pgAdmin 4 when running
(eg. user->users, order->orders)
create table users (
	email varchar(75),
	passwords varchar(75),
	first_name varchar(50),
	last_name varchar(75),
	primary key(email)
);

create table customer (
	email varchar(75) references users(email)
);

create table employee (
	email varchar(75) references users(email)
);

create table address (
	addr_no varchar(6),
	street varchar(100),
	apt_no varchar(4),
	city varchar(100),
	states varchar(50),
	country varchar(50),
	post_code varchar(10),
	primary key (addr_no,street,city,country,post_code)
);

create table publisher (
	pub_name varchar(75),
	email varchar(75),
	bank_acct varchar(75),
	primary key(pub_name)
);

create table publisher_phone (
	pub_name varchar(75) references publisher(pub_name),
	area_code varchar(5),
	phone_num varchar(10),
	primary key(area_code, phone_num)
);

create table orders (
	order_ID serial,
	date_ordered timestamp,
	primary key(order_ID)
);	

create table warehouse (
	name varchar(75),
	primary key(name)
);

create table book (
	ISBN numeric(13,0),
	title varchar(75),
	first_name varchar(50),
	last_name varchar(75),
	genre varchar(50),
	price numeric(5,2),
	percent numeric(4,2),
	primary key(ISBN)
);

create table user_addr (
	email varchar(75) references users(email),
	addr_no varchar(6),
	street varchar(100),
	city varchar(100),
	country varchar(50),
	post_code varchar(10),
	foreign key (addr_no, street, city, country,post_code) references address(addr_no, street, city, country,post_code)
);

create table war_addr (
	name varchar(75) references warehouse(name),
	addr_no varchar(6),
	street varchar(100),
	city varchar(100),
	country varchar(50),
	post_code varchar(10),
	foreign key (addr_no, street, city, country,post_code) references address(addr_no, street, city, country,post_code)
);

create table pub_addr (
	name varchar(75) references publisher(pub_name),
	addr_no varchar(6),
	street varchar(100),
	city varchar(100),
	country varchar(50),
	post_code varchar(10),
	foreign key (addr_no, street, city, country,post_code) references address(addr_no, street, city, country,post_code)
);

create table pub_book (
	name varchar(75) references publisher(pub_name),
	ISBN numeric(13,0) references book(ISBN)
);

create table basket (
	ISBN numeric(13,0) references book(ISBN),
	email varchar(75) references users(email),
	num numeric(3,0)
);

create table customer_or (
	order_no serial references orders(order_no),
	email varchar(75) references users(email),
	addr_no varchar(6),
	street varchar(100),
	city varchar(100),
	country varchar(50),
	post_code varchar(10),
	foreign key (addr_no, street, city, country,post_code) references address(addr_no, street, city, country,post_code)
);

create table order_book (
	order_no serial references orders(order_no),
	ISBN numeric(13,0) references book(ISBN),
	num numeric(2,0)
);
